CREATE SEQUENCE SEQ_FREEBOARD_NO NOCACHE NOCYCLE;
DROP SEQUENCE SEQ_FREEBOARD_NO;

DROP TABLE FREE_BOARD CASCADE CONSTRAINTS;
CREATE TABLE FREE_BOARD
(
    NO              NUMBER          NOT NULL CONSTRAINT PK_BOARD_NO PRIMARY KEY
    ,TITLE          VARCHAR2(1000)  NOT NULL
    ,CONTENT        VARCHAR2(4000)  NOT NULL
    ,ENROLL_DATE    TIMESTAMP       DEFAULT SYSDATE
    ,MODIFY_DATE    TIMESTAMP       DEFAULT SYSDATE
    ,DELETE_YN      CHAR(1)         DEFAULT 'N'
    ,WRITER_NO      NUMBER          
);

--외래키 추가
ALTER TABLE FREE_BOARD
ADD CONSTRAINT FK_FREE_BOARD_MEMBER
FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);

