--미니과제 공지사항

--시퀀스

DROP SEQUENCE SEQ_ANNOUNCEMENT_NO;
CREATE SEQUENCE SEQ_ANNOUNCEMENT_NO NOCACHE NOCYCLE;



DROP TABLE ANNOUNCEMENT CASCADE CONSTRAINTS;
--테이블 생성
CREATE TABLE ANNOUNCEMENT(
    NO              NUMBER          
    , TITLE         VARCHAR2(100)   NOT NULL
    , CONTENT       VARCHAR2(100)   NOT NULL
    , CATEGORY      VARCHAR2(100)   NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE NOT NULL
    , MODIFY_DATE   TIMESTAMP       DEFAULT SYSDATE NOT NULL
    , DEL_YN        CHAR(1)         DEFAULT 'N' CONSTRAINT CK_ANNOUNCEMENT_DELYN CHECK( DEL_YN IN ('Y','N')  )
);

--게시글 작성 (데이터)
INSERT INTO ANNOUNCEMENT(NO, TITLE, CONTENT,CATEGORY) VALUES(SEQ_ANNOUNCEMENT_NO.NEXTVAL , '이용안내사항','처음 사용하시는 분은 회원가입을 해주시기 바랍니다' , '안내사항');
INSERT INTO ANNOUNCEMENT(NO, TITLE, CONTENT,CATEGORY) VALUES(SEQ_ANNOUNCEMENT_NO.NEXTVAL , '계좌입금시 안내사항', '입금 받으실 계좌에 입력후 입금까지 1일의 시간이 소요됩니다', '입금안내');
INSERT INTO ANNOUNCEMENT(NO, TITLE, CONTENT,CATEGORY) VALUES(SEQ_ANNOUNCEMENT_NO.NEXTVAL , '등급산정의안내', '등급산정에 따른 기준표는 기기안의 기준표를 참고해주시기 바랍니다.', '등급산정');
INSERT INTO ANNOUNCEMENT(NO, TITLE, CONTENT,CATEGORY) VALUES(SEQ_ANNOUNCEMENT_NO.NEXTVAL , '게시판 이용수칙', '게시판 이용시 운영정책에 따라 게시글이 삭제가 될수 있습니다', '게시판이용수칙');
INSERT INTO ANNOUNCEMENT(NO, TITLE, CONTENT,CATEGORY) VALUES(SEQ_ANNOUNCEMENT_NO.NEXTVAL , '중고폰판매기기를 이용해주시는분들께 감사합니다.', '어쩌구저쩌구~환영합니다', '환영합니다');

--게시글 작성
INSERT INTO ANNOUNCEMENT(NO, TITLE, CONTENT,CATEGORY) VALUES(SEQ_ANNOUNCEMENT_NO.NEXTVAL , ?, ?, ?);

--게시글 수정(번호로조회해서 제목,내용)
UPDATE ANNOUNCEMENT SET TITLE = ? , CONTENT = ? , MODIFY_DATE = SYSDATE WHERE NO = ?;

--게시글 전체 조회
SELECT * FROM ANNOUNCEMENT ORDER BY NO DESC;

--게시글 상세 조회
SELECT * FROM ANNOUNCEMENT WHERE NO = ?;

--게시글 상세조회(카테고리)
SELECT * FROM ANNOUNCEMENT WHERE CATEGORY LIKE '%?%' ;

--게시글 상세조회(제목)
SELECT * FROM ANNOUNCEMENT WHERE TITLE LIKE '%?%';

-- 게시글 상세조회(내용)
SELECT * FROM ANNOUNCEMENT WHERE CONTENT LIKE '%?%';

-- 게시글 삭제 (관리자 만 가능)
UPDATE ANNOUNCEMENT SET DEL_YN = 'Y' , MODIFY_DATE = SYSDATE WHERE NO = ?;



