
-- 시퀀스 삭제

DROP SEQUENCE SEQ_FAQ_NO;

-- 시퀀스 생성

CREATE SEQUENCE SEQ_FAQ_NO NOCACHE NOCYCLE;


-- 테이블 삭제 

DROP TABLE FAQ CASCADE CONSTRAINTS;


-- 테이블 생성

CREATE TABLE FAQ(
    NO              NUMBER         CONSTRAINT PK_FAQ_NO PRIMARY KEY
    , TITLE         VARCHAR2(100)   CONSTRAINT NN_FAQ_TITLE NOT NULL
    , CONTENTS       VARCHAR2(4000) CONSTRAINT NN_FAQ_CONTENTS NOT NULL
    ,CATEGORY       VARCHAR2(100)   CONSTRAINT NN_FAQ_CATEGORY NOT NULL
    , ENROLL_DATE   TIMESTAMP       DEFAULT SYSDATE
    , MODIFY_DATE   TIMESTAMP       
    , DEL_YN        CHAR(1)         DEFAULT 'N' CONSTRAINT CK_FAQ_DELYN CHECK( DEL_YN IN ('Y','N')  )
);


-- 외래키 추가 

--ALTER TABLE FAQ
--ADD CONSTRAINT FK_FAQ_MEMBER
--FOREIGN KEY (WRITER_NO) REFERENCES MEMBER(NO);


--자주묻는질문 미리 작성
INSERT INTO FAQ( NO, TITLE, CONTENTS,CATEGORY)VALUES(1,'판매시 가격은 어떻게 결정되나요?', '스크래치,배터리효율을 고려하여 가격이 측정됩니다', '가격결정문의');
INSERT INTO FAQ( NO, TITLE, CONTENTS,CATEGORY)VALUES(2,'중고 휴대폰을 판매한 후에는 어떻게 될까요?', '판매된 휴대폰은 업체에서 정리되고 재활용되거나 재판매될 수 있습니다.', '판매이후 문의');
INSERT INTO FAQ( NO, TITLE, CONTENTS,CATEGORY)VALUES(3,'중고 휴대폰을 판매하기 전에 어떤 준비를 해야 하나요?', ' 판매 전에 휴대폰을 완전히 초기화하여 개인 정보와 데이터를 삭제하는 것이 중요합니다.', '판매 전 준비문의');

--게시글 전체 조회(최신순)
SELECT * FROM FAQ ORDER BY ENROLL_DATE DESC, MODIFY_DATE DESC;

--제목으로 검색
SELECT *FROM FAQ WHERE TITLE LIKE '%?%';
--내용으로 검색
SELECT *FROM FAQ WHERE CONTENTS LIKE '%?%';

--관리자-게시글 작성
INSERT INTO FAQ( NO,TITLE,CONTENTS,CATEGORY) VALUES( 3+SEQ_FAQ_NO.NEXTVAL , ?, ?, ?);
--관리자-게시글 수정
UPDATE FAQ SET TITLE = ? , CONTENTS = ? ,CATEGORY=?, MODIFY_DATE = SYSDATE WHERE NO = ?;
--관리자-게시글 삭제
UPDATE FAQ SET DEL_YN = 'Y' , MODIFY_DATE = SYSDATE WHERE NO = ?;


COMMIT;
------------
